### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/daemon-disqualifier#18]
This should be standardized in our SDK but we can do a manual implementation here. The metadata header schema is as follows:
```
<!-- Ubiquity - CLASSNAME - FUNCTION_CALLER - REVISION
```
`CLASSNAME` a developer defined "class name" that can provide useful context of what operation is being performed. 
`FUNCTION_CALLER` the name of the function that was run. Could be useful to start investigation for debugging. 
`REVISION` no longer works, but was supposed to be a revision hash. 

Now, I think it makes sense to do something like: 

```
<!-- UbiquityOS - Followup - remindAssignees - @ubiquibot/conversation-rewards@9de94e814df3dbf0829cb5d072979bc36fee3dd7
```
1. Ubiquity -> UbiquityOS
2. Revision hash clearly states the plugin name and the revision hash. We used to do shorthand revision hash, not sure if that is better than the full one. It sure does make the header border clear. 

---
> @sshivaditya2019, this task has been idle for a while. Please provide an update.
> 
> 
```html
<!-- Ubiquity - Followup - remindAssignees - undefined
{
  "taskAssignees": [
    53160903
  ],
  "caller": "remindAssignees"
}
-->
```

> @gentlementlegen Really nice to see this finally working as expected. Except the revision hash in the metadata is undefined. This should be fixed!

---

_Originally posted by @0x4007 in https://github.com/ubiquibot/conversation-rewards/issues/97#issuecomment-2340237317_

**Comment by gentlementlegen** [comment]
I think it might be safer to use some JSON metadata or any other format that prevent manual parsing. I am seing the use of `-` separator here that could break if any `-` is contained within the metadata content.

**Comment by 0x4007** [comment]
The metadata parser was already built and works as expected. It regex targets the metadata header and then parses the JSON inside as expected.

**Comment by gentlementlegen** [comment]
I think the steps for solving this would be to start using the SDK that has it built-in, so it doesn't need to be manually added to this plugin.

**Comment by gentlementlegen** [comment]
I think this can be closed since we are now using the SDK and the metadata is handled there.
