### ISSUE TITLE
Follow up enhancements

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/daemon-disqualifier#23]
1. Follow up should be on pull request so that they don't reply under issue and get paid for it. 
2. If there isn't a pull request open in time for the warning, automatically disqualify them (they should open a draft pull as soon as they self assign)
   - Must be configurable since some tasks are not coding related. 
   - If pull isn't required then follow up under issue as we do now. 
3. "activity which should be considered is only the one from the assignees themselves. I believe currently any activity from anyone is considered in the events."

**Comment by gentlementlegen** [comment]
I think we can also add the point that the activity which should be considered is only the one from the assignees themselves. I believe currently any activity from anyone is considered in the events.

**Comment by 0x4007** [comment]
I think repo scoped is probably fine for now

**Comment by gentlementlegen** [comment]
Maybe we should start using [Discussions](https://docs.github.com/en/discussions/quickstart) for issues that do not require pull-request, and add the capability to incentivize these. I'll do that repo scoped in the meantime then.

**Comment by 0x4007** [comment]
> If we comment on the PR, we should also consider the case when multiple PRs are opened. Should all of them get the reminder?

Makes sense, and the disqualified candidates should have theirs closed so no more reminders. 

Discussions might make sense to use! We tried back a couple years ago to use discussions as "proposals" but evolved the system to stay inside of issues and get them funded to make them "official tasks."

**Comment by 0x4007** [comment]
I realize that we will lose a lot of other plugin capabilities by switching over to discussions. So it might not be a good idea. 

Alternatively we upgrade every plugin to support discussions, which also doesn't seem like a good idea. 

Like daemon-pricing comes to mind.

**Comment by gentlementlegen** [comment]
I think we could implement our plugins to support discussions. Discussions have tags as well so our logic could apply there, amd closing the discussions, what we miss is the collection of comments: https://github.com/Meniole/conversation-rewards/discussions/25
