### ISSUE TITLE
Use Full Webhook Names

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/daemon-disqualifier#29]
Looks like this was never fixed. Should use full webhook names.

Using new shortened versions decreases maintainability because it can lead to developer confusion.

https://github.com/ubiquity-os-marketplace/daemon-disqualifier/blob/9ca3f7ba20a48385151a55e7cf52e57cafa9cf65/tests/main.test.ts#L67

_Originally posted by @0x4007 in https://github.com/ubiquity-os-marketplace/daemon-disqualifier/pull/22#discussion_r1794931278_

**Comment by ariesgun** [comment]
@0x4007 , calling `/start` does not seem to update the status in https://github.com/ubiquity/devpool-directory/issues/1716.
Is that normal?

**Comment by 0x4007** [comment]
> @0x4007 , calling `/start` does not seem to update the status in https://github.com/ubiquity/devpool-directory/issues/1716.
> 
> Is that normal?

I am pretty sure I broke the backend the other day. Hope to fix that soon.

**Comment by Keyrxng** [comment]
This can be closed as not planned as it was implemented as requested. The timeline objects do not use the entire webhook event name and so I have had to build a map in order for it to work.

https://github.com/ubiquity-os-marketplace/daemon-disqualifier/blob/e7d73828735af3b820228f84208aafd906d82e1d/src/types/plugin-input.ts#L47

**Comment by gentlementlegen** [comment]
@Keyrxng So you're saying that `timeline` event names do not match `GitHub's` ones if I understand correctly?

**Comment by gentlementlegen** [comment]
@0x4007 I guess this can be closed as not planned.
