### ISSUE TITLE
Fix default for eventWhitelist and Decode

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/daemon-disqualifier#32]
When left blank, the configuration complains about missing `eventWhitelist`. When giving values, it seems to decode them improperly, cf run : https://github.com/ubiquity-os-marketplace/daemon-disqualifier/actions/runs/11316394599/job/31468631289#step:5:93

**Comment by 0x4007** [comment]
You set priority I have no idea of the context of this problem

**Comment by gentlementlegen** [comment]
@0x4007 Not sure if that should be founded since it is supposed to work. See the runs that are always failing: https://github.com/ubiquity-os-marketplace/daemon-disqualifier/actions/runs/11319089020/job/31474614733

**Comment by gentlementlegen** [comment]
I'll also add the plugin build step to make this spec worth.
