### ISSUE TITLE
Interesting, I guess no message should have been posted.

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/daemon-disqualifier#47]
Interesting, I guess no message should have been posted.

_Originally posted by @gentlementlegen in https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/170#issuecomment-2480588496_

**Comment by gentlementlegen** [comment]
Duplicate of #60

**Comment by 0x4007** [comment]
@sshivaditya2019 I wonder if we should exclude closed as unplanned from the vector embeddings search results. 

These are marked as invalid tasks essentially.
