### ISSUE TITLE
Pull Request State Adjustments

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/daemon-disqualifier#59]
- When a follow up occurs, the pull request should be turned into a draft.
- If it is already a draft, only leave the follow up message.[^01^] 
- When a disqualification occurs, the pull request should be closed. 

Context: https://github.com/ubiquity-os/plugins-wishlist/issues/60#issuecomment-2516409360

Rationale: when a contributor converts from draft to ready, then that signals it is ready for review. 

[^01^]: ⚠ 52% possible duplicate - [Reviewer Follow Ups](https://www.github.com/ubiquity-os-marketplace/daemon-disqualifier/issues/49#49)

**Comment by gentlementlegen** [comment]
Just to make sure, when the PR is converted back to a draft it still sends a reminder message correct?

The closing of the pull-request is currently handled by https://github.com/ubiquity-os-marketplace/command-start-stop.

**Comment by 0x4007** [comment]
> Just to make sure, when the PR is converted back to a draft it still sends a reminder message correct?

Yes

> The closing of the pull-request is currently handled by https://github.com/ubiquity-os-marketplace/command-start-stop.

When disqualified it needs to close the pull

**Comment by whilefoo** [comment]
What if the user is waiting for a PR review? in that case it doesn't make sense to turn it into draft

**Comment by 0x4007** [comment]
> What if the user is waiting for a PR review? in that case it doesn't make sense to turn it into draft

Let me try and think through the scenarios, ✅ means "success condition" or the assignee is not at fault and should not be penalized:

- Assignee just opened a pull and nobody reviewed yet. ✅[^1^]
- Assignee received an approval. ✅
- Assignee received a rejection. ❌
- Assignee received a review comment. ❌
- Assignee stopped commenting or committing, excluding one of the previously defined success conditions. ❌

[^1^]: The follow ups are handy for reviewers to be nudged in their notifications. They work even as is reminding the assignee but perhaps it makes more sense to nudge the issue author in the pull. I suppose this should effectively pause the timer while nudging the collaborators.

**Comment by gentlementlegen** [comment]
I think it should be only for explicit rejection (as in "requested changes"). There are plenty of times we comment for a clarification or simple questions, which are not negative / requesting changes.

**Comment by 0x4007** [comment]
> I think it should be only for explicit rejection (as in "requested changes"). There are plenty of times we comment for a clarification or simple questions, which are not negative / requesting changes.

It's not accepted so there is work they need to do, even if it means to answer the question.

**Comment by gentlementlegen** [comment]
@0x4007 Correct but the need of answering a question should not turn the pull-request into a draft no? Because the pull-request code itself won't change, that was my reasoning.

**Comment by gentlementlegen** [comment]
All right then I will proceed with the following changes on the pull-request:
- the PR will be converted to draft only if there are reviews in "changes requested" state
- otherwise, only the reminder will be posted and no state change will occur on the pull-request

Sounds good?
