### ISSUE TITLE
Only draft the pull-request if a review was requested

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/daemon-disqualifier#64]
All right then I will proceed with the following changes on the pull-request:
- the PR will be converted to draft only if there are reviews in "changes requested" state
- otherwise, only the reminder will be posted and no state change will occur on the pull-request

Sounds good?

_Originally posted by @gentlementlegen in https://github.com/ubiquity-os-marketplace/daemon-disqualifier/issues/59#issuecomment-2535819991_
            

Instead of always converting the PR to a draft, it should only happen if changes were requested by reviewers.[^01^]

[^01^]: ⚠ 51% possible duplicate - [Pull Request State Adjustments](https://www.github.com/ubiquity-os-marketplace/daemon-disqualifier/issues/59#59)

**Comment by 0x4007** [comment]
> ```diff
> ! Error: Error: No labels are set.
> ```
> 
> 
> 

I'm not sure why or how these slip in only after passing QA but obviously we need to fix

**Comment by gentlementlegen** [comment]
Probably when switched from the plugin posting the the SDK actually posting, this is considered as a thrown error and gets posted, so I believe this function should not throw.
